//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiItNews.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ItNewsEntities : DbContext
    {
        public ItNewsEntities()
            : base("name=ItNewsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Api> Api { get; set; }
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<Gestionner> Gestionner { get; set; }
        public virtual DbSet<Journalistes> Journalistes { get; set; }
        public virtual DbSet<Pub> Pub { get; set; }
        public virtual DbSet<RedacteurEnChef> RedacteurEnChef { get; set; }
        public virtual DbSet<Commentaire> Commentaire { get; set; }
    }
}
